adessoSE/Seed-Test

backend/features/step_definitions/stepdefs.js, backend/package-lock.json, backend/src/database/stepTypes.js, frontend/package-lock.json
Added new step type so i can see the text, and added all new steps to step…
=> Added new step type

backend/debug.log, backend/features/step_definitions/stepdefs.js, backend/src/database/mongodatabase.js, backend/src/database/stepTypes.js, backend/src/serverRouter/userRouter.js
- added stepType "wait"
- added stepType "checkox"
- renamed old stepType "checkox" to "ListSelection"
=> Step types update

backend/package-lock.json, backend/package.json, backend/src/database/mongodatabase.js, backend/src/serverHelper.js, backend/src/serverRouter/jiraRouter.js, backend/src/serverRouter/userRouter.js, frontend/src/app/Services/api.service.ts, frontend/src/app/account-managment/account-managment.component.html, frontend/src/app/account-managment/account-managment.component.ts, frontend/src/app/app.component.ts, frontend/src/app/login-form/login-form.component.html, frontend/src/app/login-form/login-form.component.ts
added password management,
added "repo_type" for storiesin DB
changed "issue-number" for jira-stories to issue.key
=> Jira-Login Fix

frontend/src/app/account-management/account-management.component.ts
storage listener hat nicht reagiert daher polling
=> SessionStorage polling

backend/package-lock.json, backend/package.json, backend/src/database/mongodatabase.js, backend/src/serverHelper.js
TestReports now will be seperated in ReportData an the actual Report. If the actual Report ist bigger than 16MB it will be saved in chunks via Gridfs
=> GridFSFeature implemented

frontend/package-lock.json, frontend/src/app/modals/repo-swich/repo-swich.component.html, frontend/src/app/modals/repo-swich/repo-swich.component.ts
Implemented for Jira, GitHub & custom repo
=> Icons depending on project source

frontend/src/app/modals/add-block-form/add-block-form.component.css, frontend/src/app/modals/change-jira-account/change-jira-account.component.css, frontend/src/app/modals/create-custom-project/create-custom-project.component.css, frontend/src/app/modals/create-new-group/create-new-group.component.css, frontend/src/app/modals/create-new-story/create-new-story.component.css, frontend/src/app/modals/create-new-story/create-new-story.component.html, frontend/src/app/modals/create-scenario/create-scenario.component.css, frontend/src/app/modals/create-scenario/create-scenario.component.html, frontend/src/app/modals/delete-account/delete-account.component.css, frontend/src/app/modals/new-step-request/new-step-request.component.css, frontend/src/app/modals/rename-scenario/rename-scenario.component.css, frontend/src/app/modals/rename-story/rename-story.component.css, frontend/src/app/modals/rename-story/rename-story.component.html, frontend/src/app/modals/repo-swich/repo-swich.component.css, frontend/src/app/modals/repo-swich/repo-swich.component.html, frontend/src/app/modals/save-block-form/save-block-form.component.css, frontend/src/app/modals/update-group/update-group.component.css, frontend/src/app/modals/workgroup-edit/workgroup-edit.component.css, frontend/src/app/modals/workgroup-edit/workgroup-edit.component.html, frontend/src/app/modals/workgroup-edit/workgroup-edit.component.ts, frontend/src/app/stories-bar/stories-bar.component.css, frontend/src/app/story-editor/story-editor.component.css, frontend/src/styles.scss
z-index issue solved + modals scrollbar style update
=> Bug fixes modals

frontend/src/app/app.component.ts, frontend/src/app/app.module.ts
except getBackendinfo all requests are logged
=> Fix logger404

backend/src/database/DbServices.js, backend/src/serverHelper.js, backend/src/serverRouter/mongoRouter.js, backend/src/serverRouter/storyRouter.js, backend/src/serverRouter/userRouter.js
=> 1.6clean back

backend/src/serverHelper.js
check each user controlled value before building request
=> check user controlled data

backend/src/serverHelper.js
Bug fixes for normal operation of reports
=> Bugfix find no report

backend/src/serverHelper.js, backend/src/serverRouter/userRouter.js, frontend/src/app/login/login.component.ts
=> GitHub login bug

backend/src/serverHelper.js
solved inconcistencies in function call.
=> updated function call

frontend/src/app/modals/rename-story/rename-story.component.ts
=> return correct value

backend/src/database/DbServices.js
that is the final solution to the bug
=> keep immutable _id as ObjectId

frontend/src/app/base-editor/base-editor.component.css, frontend/src/app/base-editor/base-editor.component.html, frontend/src/app/directives/resize-input.directive.ts
Reverts adessoSE/Seed-Test#336
=> Revert "Cuc 343 zentralisierte eingabefelder"

backend/src/database/DbServices.js, backend/src/serverHelper.js
correct last Scenario status in currently only shown after reloading the page
=> update status correct in db

backend/spec/mongodatabase.spec.js, backend/spec/server-vJest.spec.js, backend/spec/server.spec.js, backend/spec/serverHelper.spec.js, backend/src/serverHelper.js
- write .feature File before Export to get latest Version
- add Story description and Scenario comments to it 
- formatted Tests
=> write .feature File before Export to get latest Version

backend/src/serverHelper.js, backend/src/serverRouter/storyRouter.js, frontend/src/app/Services/management.service.ts, frontend/src/app/account-management/account-management.component.css, frontend/src/app/account-management/account-management.component.html, frontend/src/app/account-management/account-management.component.ts
Als Nutzer möchte ich beim Export optional eine Version der Testfälle angeben können, um sie versioniert sichern zu können.
Akzeptanzkriterien:
Version wird im Titel des exportierten Zip verwendet (XXX-v{Version})
Version wird  im Titel der exportierten .feature Files verwendet (XXX-v{Version})
____________________________________________________________________________________________
SingleFeature Download könnte man auch anpassen; da aber gerade nicht genutzt und keine Debugging Möglichkeit, lasse ich das lieber.
=> Cuc 380 export versioning

backend/features/step_definitions/stepdefs.js
with this change css color values can only be given in hex format #rrggbb
=> support hexcolor in check css

backend/src/serverHelper.js
Check added before running tests to see if the feature file exists and create one if not.
=> fixed save bug

.github/workflows/CI_Tests_and_Report.yaml, .github/workflows/SonarCloud-PR.yaml, actions/fullReport/action.yaml, actions/fullReport/indexReport.js, actions/notifyTeams/action.yaml, actions/notifyTeams/indexNotify.js, backend/src/helpers/reporting.ts, backend/src/server.js, backend/src/serverRouter/sanityTest.js
Deployment, testing and reporting actions
=> CUC-384-Github-Actions

frontend/src/app/scenario-editor/scenario-editor.component.ts, frontend/src/app/stories-bar/stories-bar.component.html, frontend/src/app/stories-bar/stories-bar.component.ts, frontend/src/app/story-editor/story-editor.component.ts
switch editor to next senario in story, or disable editor if no scenario present after delete.
=> Cuc 508 swich scen at del

backend/src/serverHelper.js
if the latest Scenario has status true check if all scenarios are true thus the story Status should be true, else false
=> Fix story status

frontend/src/app/Services/story.service.ts, frontend/src/app/stories-bar/stories-bar.component.css, frontend/src/app/stories-bar/stories-bar.component.html
-additionally fixed toTicket function of redirecting to the correct link(only Github)
=> Stories-bar icon&filter for Assignee removed

backend/features/step_definitions/stepdefs.js
check download on windows & docker
=> download directory os related

backend/src/helpers/reporting.ts, backend/src/serverHelper.js
Multible Scenario din't work in Story mode and could not execute due to missing world parameters. Also Fixed Problem with creating report for multible Scenario in Story mode.
=> Fix MultibleScenario Run

backend/features/step_definitions/stepdefs.js
better error messages, no more stack
=> better error messages

backend/src/serverHelper.js
Add Example lines to feature files ony if they are filled with values.
Prevent the execution of scenario example where no value is present.
=> execute only filled Examples

backend/src/serverHelper.js
examples need to be defined outside the Block.
=> don't include examples in Blocks

backend/src/serverHelper.js
Solve CUC-671
not in all JIRA scenarios is the propery scenario.comment pressent, thus beeing not a defined null but undefined.
=> not null or undefined

backend/features/step_definitions/stepdefs.js
is now Typing Key by Key 
other solutions didn't reliably work.
=> Cuc 590 send key bug

backend/features/step_definitions/stepdefs.js
Reverts adessoSE/Seed-Test#641
=> Revert "Cuc 590 send key bug"

frontend/src/app/Services/block.service.ts, frontend/src/app/base-editor/base-editor.component.html, frontend/src/app/base-editor/base-editor.component.ts
Reverts adessoSE/Seed-Test#652
=> Revert "Cuc 643 copying reject editing of ms"

frontend/src/app/base-editor/base-editor.component.html, frontend/src/app/modals/add-block-form/add-block-form.component.css, frontend/src/app/modals/edit-block/edit-block.component.css, frontend/src/app/modals/file-explorer-modal/file-explorer-modal.component.css, frontend/src/app/modals/import-modal/import-modal.component.css, frontend/src/app/modals/new-step-request/new-step-request.component.css, frontend/src/app/modals/save-block-form/save-block-form.component.css, frontend/src/app/modals/workgroup-edit/workgroup-edit.component.css, frontend/src/styles.scss
Bitte noch mal checken, ob das Info-Icon überall in Light Mode da ist.
=> CUC-651-hover-in-light-mode-nicht-erkennbar

backend/package-lock.json, backend/package.json, frontend/package-lock.json, frontend/package.json
tslib  ^2.6.3  →  ^2.7.0
Backend:
selenium-webdriver  ^4.23.0  →  ^4.24.0
Audit fixes und Cucumber-html-reporter override
=> Frontend und Backend Package update
